### ISSUE TITLE
Responsive von z.B. login

### ISSUE THREAD

**Issue by danielhoover** [DanielGasserFH/TheClickTest#1]
Guten Morgen Herr Gasser,

eine Antwort auf Ihre Frage von gestern Abend:

Das ganze responsive zu machen ist nicht so schwer wie Ihnen das vielleicht gerade erscheinen mag. Aktuell arbeiten Sie z.B. mit einem div.loginForm das Sie absolute positioniert haben. Sie können den gleichen Positionierungseffekt auch mittels Bootstrap durch die Definition eines Grids erreichen.

In z.B. Ihrer login.html müssten Sie das Markup wie folgt anpassen um einen Effekt zu erreichen wie Sie ihn sich vorstellen:

```html
<div class="container">
    <!-- einkommentieren falls Ihnen der Abstand nach oben nicht reicht -->
    <!--<div class="row">
        <div class="col-12 pt-lg-5 d-xs-none d-lg-block"></div>
    </div>-->
    <div class="row">
        <div class="col-lg-1 d-xs-none d-lg-block"></div>
        <div class="col-lg-4 col-xs-12 pt-lg-5 mt-lg-5">
            <form class="loginForm">
                <div class="hintergrundBlack">
                    <h2>Login</h2>
                    <div class="form-group">
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="E-mail / Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>
                    <button type="button" class="btn btn-success" onclick="window.location.href='main.html'">Login</button>
                    <div class="social">
                        <p> or login with social media</p>
                    </div>

                    <div class="netzwerke">
                        <a href="www.facebook.com" target="_blank"> <img src="Bilder/facebook.png"  width="150" height="43" alt="Facebook" /></a>
                        <a href="www.twitter.com" target="_blank"> <img src="Bilder/twitter.png" width="150" height="43" alt="Twitter" /></a>
                        <a href="www.google.com" target="_blank"> <img src="Bilder/google_plus.png" width="150" height="43" alt="Google" /></a>
                    </div>

                    <div class="signIn">
                        <p>Don´t have an account? <a href="registierung.html"> Register</a></p>
                    </div>

                </div>

            </form>
        </div>
        <div class="col-lg-12 d-xs-none d-md-block"></div>
    </div>
</div>

```

Im SCSS müssten Sie dann noch in Ihrer index.scss den Teil

```scss
.loginForm{
  /*width: 24%;
  position: absolute;
  top: 200px;
  left: 250px;*/

          h2{
            font-size: 40px;
            color: $white;
            text-align: center;
            margin-bottom: 50px;
            font-family: Verdana;
            }


            label{
              font-weight: bold;
              color: $white;
            }

            .form-check label{
              color: $white;
              font-size: 12px;
            }

}
``` 

auskommentieren.

Sollte Ihnen der Abstand nach oben nicht genug sein kommentieren Sie einfach das Markup oben drüber (also das div.row etc.) einfach ein.

Ich hoffe ich konnte Ihre Frage damit beantworten und Ihnen zeigen, dass das responsive machen nicht so schwer ist wie Sie es sich eventuell vorgestellt haben, sofern Sie auch Bootstrap dafür einsetzen.

Herzliche Grüße
Daniel Hoover
